<a href="https://colab.research.google.com/github/cmharr1r/Intro-to-DS-Project/blob/main/Numpy_Tutorial_Live.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print (e)

1
2
3


In [5]:
for e in A:
  print(e)


1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
L + [5]

[1, 2, 3, 4, 5]

In [11]:
A + np.array([4])

array([5, 6, 7])

In [12]:
A + np.array([4,5,6])

array([5, 7, 9])

In [14]:
A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [15]:
2 * A

array([2, 4, 6])

In [16]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
L2 = []
for e in L:
  L2.append(e + 3)

In [19]:
L2

[4, 5, 6, 7]

In [20]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [21]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [22]:
L2 = []
for e in L:
  L2.append(e**2)


In [23]:
L2

[1, 4, 9, 16]

In [24]:
A**2

array([1, 4, 9])

In [25]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [26]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [27]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [28]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])